In [181]:
import torch
torch.__version__

'2.11.0+cu128'

In [182]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [183]:
scalar.ndim

0

In [184]:
# get the python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [185]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [186]:
# Check the number of dimensions of vector
vector.ndim

1

In [187]:
# Check shape of vector
vector.shape

torch.Size([2])

In [188]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [189]:
MATRIX.ndim

2

In [190]:
MATRIX.shape

torch.Size([2, 2])

In [191]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [192]:
# Check number of dimensions of TENSOR
TENSOR.ndim

3

In [193]:
# Check shape if TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [194]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.5500, 0.7606, 0.4417, 0.7007],
         [0.9485, 0.7999, 0.3625, 0.9994],
         [0.4473, 0.1394, 0.5469, 0.7475]]),
 torch.float32)

In [195]:
# create a random tensor of size (224,224,3)
random_image_size = torch.randn(size=(224,224,3))
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [196]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [197]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [198]:
zero_to_ten_deprecated = torch.range(0,10)

zero_to_ten = torch.arange(start=0,end=10,step=3)
zero_to_ten

C:\Users\user\AppData\Local\Temp\ipykernel_34008\246439967.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([0, 3, 6, 9])

In [199]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0])

In [200]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [201]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [202]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6748, 0.7857, 0.5370, 0.5974],
        [0.8508, 0.5671, 0.5938, 0.7416],
        [0.5954, 0.1597, 0.5175, 0.4636]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [203]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [204]:
tensor * 10

tensor([10, 20, 30])

In [205]:
tensor

tensor([1, 2, 3])

In [206]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [207]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [208]:
print(tensor,'*',tensor)
print("Equal:",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [209]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [210]:
tensor * tensor

tensor([1, 4, 9])

In [211]:
torch.matmul(tensor,tensor)

tensor(14)

In [212]:
tensor @ tensor

tensor(14)

In [213]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [214]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [215]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype=torch.float32)
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [216]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [ ]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:



RuntimeError: expected m1 and m2 to have the same dtype, but got: float != __int64

In [ ]:
torch.mm(tensor_A,tensor_B.T.float())

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=6)
x = tensor_A.float()
output = linear(x)
print(f"Input shape:{x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape:{output.shape}")

Input shape:torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape:torch.Size([3, 6])


In [ ]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum:{x.min()}")
print(f"Maximum:{x.max()}")
print(f"Mean:{x.type(torch.float32).mean()}")
print(f"Sum:{x.sum()}")

Minimum:0
Maximum:90
Mean:45.0
Sum:450


In [ ]:
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Create a tensor
tensor = torch.arange(10,100,10)
print(f"Tensor:{tensor}")

print(f"Index where max value occurs:{tensor.argmax()}")
print(f"Index where min value occurs:{tensor.argmin()}")

Tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs:8
Index where min value occurs:0


In [ ]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
import torch
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,0] = 5 #所有行，第0列
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape :{x_squeezed.shape}")

Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape:torch.Size([1, 7])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7.])
New shape :torch.Size([7])


In [ ]:
print(f"Previous tensor:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

Previous tensor:tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape:torch.Size([7])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape:torch.Size([1, 7])


In [ ]:
x_original = torch.randn(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket:{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket:1


In [ ]:
x[:,0]

tensor([1, 2, 3])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor,array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor,array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

#Create two random tensors
random_tensor_A = torch.randn(3,4)
random_tensor_B = torch.randn(3,4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B?")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[-0.2054,  0.1259,  0.7944,  1.0874],
        [-1.4078, -0.8208, -0.5616, -0.5870],
        [ 0.3775, -0.0128,  0.2130, -0.6137]])

Tensor B:
tensor([[-0.3619, -0.5029,  0.3480, -1.2122],
        [ 0.7990,  1.1848, -0.4147,  0.9941],
        [-2.5140, -1.5989,  0.0823, -0.6491]])

Does Tensor A equal Tensor B?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

Random_seed = 44
torch.manual_seed(Random_seed)
random_tensor_C = torch.randn(3,4)

torch.random.manual_seed(seed=Random_seed)
random_tensor_D = torch.randn(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D?")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[ 0.0589, -1.3945,  0.8448,  0.1268],
        [ 1.0822, -1.1731, -1.6887,  0.4277],
        [-0.1849,  0.9653,  0.3236,  0.4940]])

Tensor D:
tensor([[ 0.0589, -1.3945,  0.8448,  0.1268],
        [ 1.0822, -1.1731, -1.6887,  0.4277],
        [-0.1849,  0.9653,  0.3236,  0.4940]])

Does Tensor C equal Tensor D?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

Thu Jun  4 11:24:28 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.86                 Driver Version: 591.86         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti   WDDM  |   00000000:01:00.0  On |                  Off |
|  0%   46C    P8             26W /  450W |    2238MiB /  24564MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [217]:
import torch
torch.cuda.is_available()

True

In [219]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [220]:
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [221]:
# If tensor on gpu,can't transform it to Numpy(this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [222]:
# Instead,copy the tensor back to gpu
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3])